#ifndef PRC_TYPES_H
#define PRC_TYPES_H

typedef enum fnresult
{
    FN_SUCCESS,
    FN_FAILURE,
    FN_INVALID_ARGUMENT,
    FN_NO_ARGS
} fnresult_t;

enum prc_align
{
    PRC_ALIGN_NONE,
    PRC_ALIGN_TOPLEFT,
    PRC_ALIGN_TOP,
    PRC_ALIGN_TOPRIGHT,
    PRC_ALIGN_LEFT,
    PRC_ALIGN_CENTRE,
    PRC_ALIGN_RIGHT,
    PRC_ALIGN_BOTTOMLEFT,
    PRC_ALIGN_BOTTOM,
    PRC_ALIGN_BOTTOMRIGHT
};

#endif /* PRC_TYPES_H */